config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root 'main#home'
  get 'main/dashboard'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    if user_signed_in?
      redirect_to main_dashboard_path
    end
  end

  def dashboard
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/dashboard.html.erb
<div class="row">
     <div class="col-md-2">
          <div class="card my-card">
               <div class="card-block">
                 <div class="card-body">
                   <h4 class="card-title">My Bookings</h4>
                   <p class="card-text">Total Bookings: <%= current_user.bookings.count %></p>
                   <%= link_to "My Bookings", bookings_path, class: "btn btn-primary" %>
                  </div>
               </div>
          </div>
     </div>
     <div class="col-md-2">
          <div class="card my-card">
               <div class="card-block">
                 <div class="card-body">
                   <h4 class="card-title">My Profile</h4>
                   <p class="card-text">Last Updated: <%= current_user.updated_at.strftime('%Y-%m-%d') %></p>
                   <%= link_to "My Profile", edit_user_registration_path, class: "btn btn-primary" %>
                  </div>
               </div>
          </div>
     </div>
</div>

app/views/main/home.html.erb
<div class="container-fluid homepage">
  <div class="row">
    <div class="col-md-offset-4 col-md-4 main-page">
      <%= image_tag "paynearby-logo", class: "main-logo"%>
      <div class="row nav-btns">
        <div class="col-md-6">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
        </div>
        <div class="col-md-6">
          <%= link_to "SignUp", new_user_registration_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

</div>