config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root 'main#home'
  get 'main/dashboard'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :booking_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = current_user.bookings
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @rooms = Room.available_rooms
  end

  # GET /bookings/1/edit
  def edit
    @rooms = Room.available_rooms
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = current_user.bookings.new(booking_params)
    @booking.status = "Approved"
    respond_to do |format|
      if @booking.save
        @booking.room.update(is_available: false)
        @rooms = Room.available_rooms
        format.html { redirect_to bookings_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        @rooms = Room.available_rooms
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to bookings_path, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.update(status: "Canceled")
    @booking.room.update(is_available: true)
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :room_id, :status, :booking_date)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <%= form.label :room_id,  class: "control-label col-sm-2" %>
    <div class="col-sm-3">
      <%= form.select :room_id, options_from_collection_for_select(@rooms, :id, :room_no),{prompt: "Select atleast one"}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= form.label :booking_date,  class: "control-label col-sm-2" %>
    <div class="col-sm-3">
      <%= form.text_field :booking_date, class: "datepicker form-control", autocomplete: "off" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    $('.datepicker').datepicker({
      startDate: new Date(),
      endDate: "+6m",
      format: 'yyyy-mm-dd'
    });
  });
</script>

app/views/bookings/edit.html.erb
<% content_for :my_booking_class, 'active' %>
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<% content_for :my_booking_class, 'active' %>
<h1>Bookings</h1>
<%= link_to 'New Booking', new_booking_path, class: "btn btn-primary" %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Room</th>
      <th>Status</th>
      <th>Booking date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room.room_no %></td>
        <td><%= booking.status %></td>
        <td><%= booking.booking_date.strftime("%Y-%m-%d") %></td>
        <td><%= link_to 'Show', booking %></td>
        <!-- <td><%#= link_to 'Edit', edit_booking_path(booking) %></td> -->
        <td><%= link_to_if booking.status != "Canceled", 'Cancel', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookings/new.html.erb
<% content_for :my_booking_class, 'active' %>
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<% content_for :my_booking_class, 'active' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @booking.room.room_no %>
</p>

<p>
  <strong>Room Amenities: </strong>
  <ul>
    <% @booking.room.room_category.amenities.each do |amenity| %>
      <li><%= amenity.name %></li>
    <% end %>
  </ul>
</p>

<p>
    <strong>Room Price: </strong><%= number_to_currency(@booking.room.room_category.price, unit: "$") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @booking.status %>
</p>


<p>
  <strong>Booking date:</strong>
  <%= @booking.booking_date.strftime("%Y-%m-%d") %>
</p>

<%= link_to_if @booking.status != "Canceled", 'Cancel', @booking, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', bookings_path %>